<?php
// created: 2015-06-03 17:58:54
$sugar_config = array (
  'addAjaxBannedModules' => 
  array (
    0 => 'asol_Process',
    1 => 'asol_Events',
    2 => 'asol_Activity',
    3 => 'asol_Task',
    4 => 'asol_ProcessInstances',
    5 => 'asol_WorkingNodes',
    6 => 'asol_OnHold',
    7 => 'asol_Process',
    8 => 'asol_Events',
    9 => 'asol_Activity',
    10 => 'daik_jiekuangren_info',
    11 => 'liuch_fangkuang_liucheng',
    12 => 'asol_Task',
    13 => 'asol_ProcessInstances',
    14 => 'asol_WorkingNodes',
    15 => 'asol_OnHold',
    16 => 'asol_Process',
    17 => 'asol_Events',
    18 => 'asol_Activity',
    19 => 'asol_Task',
    20 => 'asol_ProcessInstances',
    21 => 'asol_WorkingNodes',
    22 => 'asol_OnHold',
    23 => 'asol_Process',
    24 => 'asol_Events',
    25 => 'asol_Activity',
    26 => 'asol_Task',
    27 => 'asol_ProcessInstances',
    28 => 'asol_WorkingNodes',
    29 => 'asol_OnHold',
    30 => 'asol_Process',
    31 => 'asol_Events',
    32 => 'asol_Activity',
    33 => 'asol_Task',
    34 => 'asol_ProcessInstances',
    41 => 'asol_WorkingNodes',
    42 => 'asol_OnHold',
    35 => 'asol_WorkingNodes',
    36 => 'asol_OnHold',
    37 => 'asol_Events',
    38 => 'asol_Activity',
    39 => 'asol_Task',
    40 => 'asol_ProcessInstances',
    48 => 'asol_Events',
    49 => 'asol_Activity',
    50 => 'asol_Task',
    51 => 'asol_ProcessInstances',
    52 => 'asol_WorkingNodes',
    53 => 'asol_OnHold',
    54 => 'yuang_fengongsi_info',
    55 => 'yuang_waibu_qudao_info',
    56 => 'daik_jinrong_jigou_info',
    43 => 'asol_OnHold',
    44 => 'asol_Process',
    45 => 'yuang_yuangong_guanli',
    46 => 'asol_OnHold',
    47 => 'asol_Process',
    57 => 'yuang_bumen_info',
    58 => 'asol_WorkingNodes',
    59 => 'asol_Process',
    60 => 'asol_Events',
    61 => 'asol_Activity',
    62 => 'asol_Task',
    63 => 'asol_ProcessInstances',
    64 => 'asol_WorkingNodes',
    65 => 'asol_OnHold',
    66 => 'asol_Process',
    67 => 'asol_Events',
    68 => 'asol_Activity',
    69 => 'asol_Task',
    70 => 'asol_ProcessInstances',
    71 => 'asol_WorkingNodes',
    72 => 'asol_OnHold',
    73 => 'asol_Process',
    74 => 'asol_Events',
    75 => 'asol_Activity',
    76 => 'asol_Task',
    77 => 'asol_ProcessInstances',
    78 => 'asol_WorkingNodes',
    79 => 'asol_OnHold',
    80 => 'asol_Process',
    81 => 'asol_Events',
    82 => 'asol_Activity',
    83 => 'asol_Task',
    84 => 'asol_ProcessInstances',
    85 => 'asol_WorkingNodes',
    86 => 'asol_OnHold',
    87 => 'asol_Process',
    88 => 'asol_Events',
    89 => 'asol_Activity',
    90 => 'asol_Task',
    91 => 'asol_ProcessInstances',
    92 => 'asol_WorkingNodes',
    93 => 'asol_OnHold',
    94 => 'asol_Process',
    95 => 'asol_Events',
    96 => 'asol_Activity',
    97 => 'asol_Task',
    98 => 'asol_ProcessInstances',
    99 => 'asol_WorkingNodes',
    100 => 'asol_OnHold',
    101 => 'asol_Process',
    102 => 'asol_Events',
    103 => 'asol_Activity',
    104 => 'asol_Task',
    105 => 'asol_ProcessInstances',
    106 => 'asol_WorkingNodes',
    107 => 'asol_OnHold',
    108 => 'asol_Process',
    109 => 'asol_Events',
    110 => 'asol_Activity',
    111 => 'asol_Task',
    112 => 'asol_ProcessInstances',
    113 => 'asol_WorkingNodes',
    114 => 'asol_OnHold',
    115 => 'asol_Process',
    116 => 'asol_Events',
    117 => 'asol_Activity',
    118 => 'asol_Task',
    119 => 'asol_ProcessInstances',
    120 => 'asol_WorkingNodes',
    121 => 'asol_OnHold',
  ),
  'admin_access_control' => false,
  'admin_export_only' => false,
  'cache_dir' => 'cache/',
  'calculate_response_time' => true,
  'calendar' => 
  array (
    'default_view' => 'week',
    'show_calls_by_default' => true,
    'show_tasks_by_default' => true,
    'show_completed_by_default' => true,
    'editview_width' => 990,
    'editview_height' => 485,
    'day_timestep' => 15,
    'week_timestep' => 30,
    'items_draggable' => true,
    'items_resizable' => true,
    'enable_repeat' => true,
    'max_repeat_count' => 1000,
  ),
  'chartEngine' => 'Jit',
  'common_ml_dir' => '',
  'create_default_user' => false,
  'cron' => 
  array (
    'max_cron_jobs' => 10,
    'max_cron_runtime' => 30,
    'min_cron_interval' => 30,
  ),
  'currency' => '',
  'dashlet_display_row_options' => 
  array (
    0 => '1',
    1 => '3',
    2 => '5',
    3 => '10',
  ),
  'date_formats' => 
  array (
    'Y-m-d' => '2010-12-23',
    'm-d-Y' => '12-23-2010',
    'd-m-Y' => '23-12-2010',
    'Y/m/d' => '2010/12/23',
    'm/d/Y' => '12/23/2010',
    'd/m/Y' => '23/12/2010',
    'Y.m.d' => '2010.12.23',
    'd.m.Y' => '23.12.2010',
    'm.d.Y' => '12.23.2010',
  ),
  'datef' => 'm/d/Y',
  'dbconfig' => 
  array (
    'db_host_name' => 'localhost',
    'db_host_instance' => 'SQLEXPRESS',
    'db_user_name' => 'root',
    'db_password' => 'MyRoot123',
    'db_name' => 'fzglsys',
    'db_type' => 'mysql',
    'db_port' => '',
    'db_manager' => 'MysqliManager',
  ),
  'dbconfigoption' => 
  array (
    'persistent' => true,
    'autofree' => false,
    'debug' => 0,
    'ssl' => false,
    'collation' => 'utf8_general_ci',
  ),
  'default_action' => 'index',
  'default_charset' => 'UTF-8',
  'default_currencies' => 
  array (
    'AUD' => 
    array (
      'name' => 'Australian Dollars',
      'iso4217' => 'AUD',
      'symbol' => '$',
    ),
    'BRL' => 
    array (
      'name' => 'Brazilian Reais',
      'iso4217' => 'BRL',
      'symbol' => 'R$',
    ),
    'GBP' => 
    array (
      'name' => 'British Pounds',
      'iso4217' => 'GBP',
      'symbol' => '£',
    ),
    'CAD' => 
    array (
      'name' => 'Canadian Dollars',
      'iso4217' => 'CAD',
      'symbol' => '$',
    ),
    'CNY' => 
    array (
      'name' => 'Chinese Yuan',
      'iso4217' => 'CNY',
      'symbol' => '￥',
    ),
    'EUR' => 
    array (
      'name' => 'Euro',
      'iso4217' => 'EUR',
      'symbol' => '€',
    ),
    'HKD' => 
    array (
      'name' => 'Hong Kong Dollars',
      'iso4217' => 'HKD',
      'symbol' => '$',
    ),
    'INR' => 
    array (
      'name' => 'Indian Rupees',
      'iso4217' => 'INR',
      'symbol' => '₨',
    ),
    'KRW' => 
    array (
      'name' => 'Korean Won',
      'iso4217' => 'KRW',
      'symbol' => '₩',
    ),
    'YEN' => 
    array (
      'name' => 'Japanese Yen',
      'iso4217' => 'JPY',
      'symbol' => '¥',
    ),
    'MXM' => 
    array (
      'name' => 'Mexican Pesos',
      'iso4217' => 'MXM',
      'symbol' => '$',
    ),
    'SGD' => 
    array (
      'name' => 'Singaporean Dollars',
      'iso4217' => 'SGD',
      'symbol' => '$',
    ),
    'CHF' => 
    array (
      'name' => 'Swiss Franc',
      'iso4217' => 'CHF',
      'symbol' => 'SFr.',
    ),
    'THB' => 
    array (
      'name' => 'Thai Baht',
      'iso4217' => 'THB',
      'symbol' => '฿',
    ),
    'USD' => 
    array (
      'name' => 'US Dollars',
      'iso4217' => 'USD',
      'symbol' => '$',
    ),
  ),
  'default_currency_iso4217' => 'USD',
  'default_currency_name' => 'US Dollars',
  'default_currency_significant_digits' => 2,
  'default_currency_symbol' => '$',
  'default_date_format' => 'm/d/Y',
  'default_decimal_seperator' => '.',
  'default_email_charset' => 'UTF-8',
  'default_email_client' => 'sugar',
  'default_email_editor' => 'html',
  'default_export_charset' => 'UTF-8',
  'default_language' => 'zh_cn',
  'default_locale_name_format' => 's f l',
  'default_max_tabs' => '7',
  'default_module' => 'Home',
  'default_navigation_paradigm' => 'gm',
  'default_number_grouping_seperator' => ',',
  'default_password' => '',
  'default_permissions' => 
  array (
    'dir_mode' => 1528,
    'file_mode' => 432,
    'user' => '',
    'group' => '',
  ),
  'default_subpanel_links' => false,
  'default_subpanel_tabs' => true,
  'default_swap_last_viewed' => false,
  'default_swap_shortcuts' => false,
  'default_theme' => 'Sugar5',
  'default_time_format' => 'h:ia',
  'default_user_is_admin' => false,
  'default_user_name' => '',
  'demoData' => 'no',
  'disable_convert_lead' => false,
  'disable_export' => false,
  'disable_persistent_connections' => 'false',
  'display_email_template_variable_chooser' => false,
  'display_inbound_email_buttons' => false,
  'dump_slow_queries' => false,
  'email_address_separator' => ',',
  'email_default_client' => 'sugar',
  'email_default_delete_attachments' => true,
  'email_default_editor' => 'html',
  'email_xss' => 'YToxMzp7czo2OiJhcHBsZXQiO3M6NjoiYXBwbGV0IjtzOjQ6ImJhc2UiO3M6NDoiYmFzZSI7czo1OiJlbWJlZCI7czo1OiJlbWJlZCI7czo0OiJmb3JtIjtzOjQ6ImZvcm0iO3M6NToiZnJhbWUiO3M6NToiZnJhbWUiO3M6ODoiZnJhbWVzZXQiO3M6ODoiZnJhbWVzZXQiO3M6NjoiaWZyYW1lIjtzOjY6ImlmcmFtZSI7czo2OiJpbXBvcnQiO3M6ODoiXD9pbXBvcnQiO3M6NToibGF5ZXIiO3M6NToibGF5ZXIiO3M6NDoibGluayI7czo0OiJsaW5rIjtzOjY6Im9iamVjdCI7czo2OiJvYmplY3QiO3M6MzoieG1wIjtzOjM6InhtcCI7czo2OiJzY3JpcHQiO3M6Njoic2NyaXB0Ijt9',
  'export_delimiter' => ',',
  'export_excel_compatible' => false,
  'history_max_viewed' => 50,
  'host_name' => 'localhost',
  'import_max_execution_time' => 3600,
  'import_max_records_per_file' => 100,
  'import_max_records_total_limit' => '',
  'installer_locked' => true,
  'jobs' => 
  array (
    'min_retry_interval' => 30,
    'max_retries' => 5,
    'timeout' => 86400,
  ),
  'js_custom_version' => 1,
  'js_lang_version' => 13,
  'languages' => 
  array (
    'en_us' => 'English (US)',
    'zh_cn' => '简体中文',
  ),
  'large_scale_test' => false,
  'lead_conv_activity_opt' => 'donothing',
  'list_max_entries_per_page' => 20,
  'list_max_entries_per_subpanel' => 10,
  'lock_default_user_name' => false,
  'lock_homepage' => false,
  'lock_subpanels' => false,
  'log_dir' => '.',
  'log_file' => 'sugarcrm.log',
  'log_memory_usage' => false,
  'logger' => 
  array (
    'level' => 'debug',
    'file' => 
    array (
      'ext' => '.log',
      'name' => 'fzglsys',
      'dateFormat' => '%c',
      'maxSize' => '10MB',
      'maxLogs' => 10,
      'suffix' => '',
    ),
  ),
  'max_dashlets_homepage' => '15',
  'name_formats' => 
  array (
    's f l' => 's f l',
    'f l' => 'f l',
    's l' => 's l',
    'l, s f' => 'l, s f',
    'l, f' => 'l, f',
    's l, f' => 's l, f',
    'l s f' => 'l s f',
    'l f s' => 'l f s',
  ),
  'passwordsetting' => 
  array (
    'SystemGeneratedPasswordON' => true,
    'generatepasswordtmpl' => '3f44b261-2282-e90b-6d8b-5542c28bc773',
    'lostpasswordtmpl' => '419f8bd5-e60e-aa7d-c474-5542c2d5d57a',
    'forgotpasswordON' => true,
    'linkexpiration' => true,
    'linkexpirationtime' => 24,
    'linkexpirationtype' => 60,
    'systexpiration' => 1,
    'systexpirationtime' => 7,
    'systexpirationtype' => '0',
    'systexpirationlogin' => '',
    'minpwdlength' => 6,
    'oneupper' => true,
    'onelower' => true,
    'onenumber' => true,
  ),
  'portal_view' => 'single_user',
  'require_accounts' => true,
  'resource_management' => 
  array (
    'special_query_limit' => 50000,
    'special_query_modules' => 
    array (
      0 => 'Reports',
      1 => 'Export',
      2 => 'Import',
      3 => 'Administration',
      4 => 'Sync',
    ),
    'default_limit' => 1000,
  ),
  'rss_cache_time' => '10800',
  'save_query' => 'all',
  'search_wildcard_char' => '%',
  'search_wildcard_infront' => false,
  'session_dir' => '',
  'showDetailData' => true,
  'showThemePicker' => true,
  'site_url' => 'http://localhost/fzglsys',
  'slow_query_time_msec' => '100',
  'sugar_version' => '6.5.20',
  'sugarbeet' => 0,
  'time_formats' => 
  array (
    'H:i' => '23:00',
    'h:ia' => '11:00pm',
    'h:iA' => '11:00PM',
    'h:i a' => '11:00 pm',
    'h:i A' => '11:00 PM',
    'H.i' => '23.00',
    'h.ia' => '11.00pm',
    'h.iA' => '11.00PM',
    'h.i a' => '11.00 pm',
    'h.i A' => '11.00 PM',
  ),
  'timef' => 'H:i',
  'tmp_dir' => 'cache/xml/',
  'tracker_max_display_length' => 15,
  'translation_string_prefix' => false,
  'unique_key' => 'fzglsys_v3',
  'upload_badext' => 
  array (
    0 => 'php',
    1 => 'php3',
    2 => 'php4',
    3 => 'php5',
    4 => 'pl',
    5 => 'cgi',
    6 => 'py',
    7 => 'asp',
    8 => 'cfm',
    9 => 'js',
    10 => 'vbs',
    11 => 'html',
    12 => 'htm',
  ),
  'upload_dir' => 'upload/',
  'upload_maxsize' => 30000000,
  'use_common_ml_dir' => false,
  'use_real_names' => true,
  'vcal_time' => '2',
  'verify_client_ip' => true,
  'disabled_languages' => 'en_us',
  'default_module_favicon' => false,
  'dashlet_auto_refresh_min' => '30',
  'enable_action_menu' => true,
  'stack_trace_errors' => false,
  'developerMode' => false,
);