<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'fzgls',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'fzgl_sys_module',
  'published_date' => '2015-04-11 08:05:02',
  'type' => 'module',
  'version' => 1428739502,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'fzgl_sys_module',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'fzgls_bumeng_mataine',
      'class' => 'fzgls_bumeng_mataine',
      'path' => 'modules/fzgls_bumeng_mataine/fzgls_bumeng_mataine.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'fzgls_employer_info',
      'class' => 'fzgls_employer_info',
      'path' => 'modules/fzgls_employer_info/fzgls_employer_info.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'fzgls_fenggongsi_info',
      'class' => 'fzgls_fenggongsi_info',
      'path' => 'modules/fzgls_fenggongsi_info/fzgls_fenggongsi_info.php',
      'tab' => true,
    ),
    3 => 
    array (
      'module' => 'fzgls_hezuo_waibu_qudao',
      'class' => 'fzgls_hezuo_waibu_qudao',
      'path' => 'modules/fzgls_hezuo_waibu_qudao/fzgls_hezuo_waibu_qudao.php',
      'tab' => true,
    ),
    4 => 
    array (
      'module' => 'fzgls_jiekuangren_dangan',
      'class' => 'fzgls_jiekuangren_dangan',
      'path' => 'modules/fzgls_jiekuangren_dangan/fzgls_jiekuangren_dangan.php',
      'tab' => true,
    ),
    5 => 
    array (
      'module' => 'fzgls_jsjg_base_info',
      'class' => 'fzgls_jsjg_base_info',
      'path' => 'modules/fzgls_jsjg_base_info/fzgls_jsjg_base_info.php',
      'tab' => true,
    ),
    6 => 
    array (
      'module' => 'fzgls_kefu_liucheng',
      'class' => 'fzgls_kefu_liucheng',
      'path' => 'modules/fzgls_kefu_liucheng/fzgls_kefu_liucheng.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fzgls_bumeng_mataine',
      'to' => 'modules/fzgls_bumeng_mataine',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fzgls_employer_info',
      'to' => 'modules/fzgls_employer_info',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fzgls_fenggongsi_info',
      'to' => 'modules/fzgls_fenggongsi_info',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fzgls_hezuo_waibu_qudao',
      'to' => 'modules/fzgls_hezuo_waibu_qudao',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fzgls_jiekuangren_dangan',
      'to' => 'modules/fzgls_jiekuangren_dangan',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fzgls_jsjg_base_info',
      'to' => 'modules/fzgls_jsjg_base_info',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fzgls_kefu_liucheng',
      'to' => 'modules/fzgls_kefu_liucheng',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/zh_cn.lang.php',
      'to_module' => 'application',
      'language' => 'zh_cn',
    ),
  ),
);